### ISSUE TITLE
SARAN

### ISSUE THREAD

**Issue by hiyapo** [MFarelS/untuk-Z#2]
KALAU MAU LANGSUNG TEMBAK AJA BANG LEWAT WA DARI PADA TULIS KYK GITU

**Comment by MFarelS** [comment]
> KALAU MAU LANGSUNG TEMBAK AJA BANG LEWAT WA DARI PADA TULIS KYK GITU
Udah Bro, Ini Hasilnya
![IMG_20201206_111503](https://user-images.githubusercontent.com/58540890/101271352-774b5a00-37b4-11eb-848a-0b85b2bbca4d.jpg)
![IMG_20201206_111543](https://user-images.githubusercontent.com/58540890/101271353-79151d80-37b4-11eb-9667-2eceb9454c5f.jpg)

**Comment by hiyapo** [comment]
> > KALAU MAU LANGSUNG TEMBAK AJA BANG LEWAT WA DARI PADA TULIS KYK GITU
> > Udah Bro, Ini Hasilnya
> > ![IMG_20201206_111503](https://user-images.githubusercontent.com/58540890/101271352-774b5a00-37b4-11eb-848a-0b85b2bbca4d.jpg)
> > ![IMG_20201206_111543](https://user-images.githubusercontent.com/58540890/101271353-79151d80-37b4-11eb-9667-2eceb9454c5f.jpg)

yang sbr bro

**Comment by MFarelS** [comment]
> > > KALAU MAU LANGSUNG TEMBAK AJA BANG LEWAT WA DARI PADA TULIS KYK GITU
> > > Udah Bro, Ini Hasilnya
> > > ![IMG_20201206_111503](https://user-images.githubusercontent.com/58540890/101271352-774b5a00-37b4-11eb-848a-0b85b2bbca4d.jpg)
> > > ![IMG_20201206_111543](https://user-images.githubusercontent.com/58540890/101271353-79151d80-37b4-11eb-9667-2eceb9454c5f.jpg)
> 
> yang sbr bro

Awokwaokwaokwaok thx mhsnk
